In [7]:
import pandas as pd 
import numpy as np
import re, nltk
from numpy import array
from keras.preprocessing.text import one_hot 
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten
from keras.layers import GlobalMaxPooling1D
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer

In [8]:
import pandas as pd
df = pd.read_csv(r'englishAmharicTigrinya2.csv', encoding ="utf-8")
df1 = df.sample(frac =1)
display(df1)

English  \
3970  Cool thing about being in college is you can g...   
4784  had to tell you that Im seeing the cleveland o...   
3898  Im covering this event for IBM tomorrow Heres ...   
5216              February 20th Same day as Kurt Cobain   
488   Amazon Prime Day Tops Biggest Black Friday for...   
...                                                 ...   
342   Decided to make the most of my Amazon Prime by...   
2809  Sat in the garden listening to some Fleetwood ...   
1509  Its Monday Get up Stand up Dont give up the fi...   
3755  Sarah Palin other women you disagree with may ...   
675   a Watch the Apple event despite having little ...   

                                                Amharic  \
3970  ኮሌጅ ስለመሆን ቀዝቀዝ ያለ ነገር ቢኖር ኢ ኦቭን እና ኮከቦች ከዚያም ጀ...   
4784  የአንተን ስሜት መረዳት እንደሚቻለው የክሌቭላንድ ኦርኬስትራ ነገ ሲመጣ ማ...   
3898  ይህንን ክንውን ለአይ ኤም ኤፍ ነገ መሸፈኛ በማድረግ ስለ አዲስዋይዮዋርክ...   
5216                          የካቲት 20ኛው የሰሜኑ ቀን ኩርቶ ኮቢን   
488   የአማዞን ጠቅላይ ፍርድ ቤት ለኩባንያዎቹ አማዞን የመጀመሪያው ጠቅላይ ሚኒ...   
...                                                 ...   
342   በ1ኛው ጊዜ ውስጥ ከባድ ጉዞ በማድረግ ላይ ያለውንና በሬይዶኖቫን ላይ ያ...   
2809  በአትክልት ስፍራው ውስጥ በሕልሙ ሲኖሩ የነበሩ አንዳንድ ፍሌትዉድ ማክ የ...   
1509  ሰኞ ዕለት በዶንት ሲወድቅ ውጊያው ቦብ ማርሌ ምርጥኖምቦክ ደስታይሞንድይ ...   
3755  አንተም የማትስማማባቸው ሌሎች ሴቶች ሣራ ፓሊን አሁንም ብሩህ አዕምሮ ያላ...   
675   ኦር ቢ ፒፕል የሚሰራው ነገር ብዙም ትኩረት ባይሰጠውም የአፕል ክስተትን ...   

                                               Tigrinya  real_class  
3970  ኣብ ኮለጅ ከም ዘለኻ ዝሑል ነገር እንተልዩካ ፡ ናብ ኢዮጵን ኮኾብን ኬድ...           0  
4784  ጽባሕ ኦርኬስትራ ክሊቭላንድ ክትርኢ ከለኻ ኣዝዩ ከም ዝሕጐስ ክትነግረካ ...           0  
3898  ነዚ ፍጻመ እዚ ብምሽፋን ፡ ጽባሕ ንኒው ዳብሊው ቶውዛርክ እንታይ ከም ዘጋጥማ           0  
5216                  መበል 20 ለካቲት ከም ኩርባ ኩባያ እትበሃል መዓልቲ           2  
488       ቀዳማይ መዓልቲ ኣማዞን ፡ ዓባይ ብላክ ዓርቢ ንኣማዞን ቀዳማይ ደረጃ ዳ           0  
...                                                 ...         ...  
342   ኵሉ እቲ ብዛዕባ ረይዶኖቫን ዝገልጽ ናይ እንግሊዝኛ ጸብጻብ ኣብ 1ይ ክፋ...           0  
2809     ኣብ ገነት ተቐሚጡ ፡ ገሊኦም ፍለተዉድ ማክቪን ነቲ ሕልሚ ይሰምዕዎ ነበሩ           0  
1509  ሰኑይ ተንሲእካ ደው በል ዶንት ንቃልሲ ቦብ ማርሊ ብሉጽንቦዶክ ናይ ሰኑይ...           0  
3755      ሳራ ፓሊን ካልኦት ዘየሰማምዓኻየን ኣንስቲ ፡ ድሙቕ ክኸውን ይኽእል እዩ           2  
675   ኦር ለ ኽፕስ ብዛዕባ ዕዮ ኣፕል ብዙሕ ተገዳስነት እኳ እንተ ዘይነበሮ ፡...           2  

[6000 rows x 4 columns]

In [25]:
sentence = df1.Tigrinya.values.tolist()
sentencee = df1.English.values.tolist()
sentiment = df1.real_class.values.tolist()


In [26]:
sentence_a = np.array(sentence)
sentence_e = np.array(sentencee)
sentiment_a =np.array(sentiment)

In [27]:
print(len(sentence_a))
print(len(sentiment_a))
print(sentiment[0:10])

6000
6000
[0, 0, 0, 2, 0, 0, 1, 2, 0, 0]


In [28]:
Comm = []
for el in sentence_a:
    sent= re.sub(r'[A-Z]+', '', el)
    sent1 = re.sub(r'[a-z]+', '',sent)
    sent2= re.sub(r'[^\w]', ' ', sent1)
    
    Comm.append(sent2)

In [29]:
print(len(Comm))
print(Comm[0:10])

6000
['ኣብ ኮለጅ ከም ዘለኻ ዝሑል ነገር እንተልዩካ   ናብ ኢዮጵን ኮኾብን ኬድካ   ረቡዕ ብ1045 ናብ ገለ ጆብስ ክትኣቱ ትኽእል ኢኻ   እዚ ድማ ዕጥቂ የብሉን', 'ጽባሕ ኦርኬስትራ ክሊቭላንድ ክትርኢ ከለኻ ኣዝዩ ከም ዝሕጐስ ክትነግረካ ነይርካ  ', 'ነዚ ፍጻመ እዚ ብምሽፋን   ጽባሕ ንኒው ዳብሊው ቶውዛርክ እንታይ ከም ዘጋጥማ', 'መበል 20 ለካቲት ከም ኩርባ ኩባያ እትበሃል መዓልቲ', 'ቀዳማይ መዓልቲ ኣማዞን   ዓባይ ብላክ ዓርቢ ንኣማዞን ቀዳማይ ደረጃ ዳ', 'ጽባሕ ሓለቓ ጋንታ ኣብ ናሽቪል   ኤሪኽ ቤተ ክርስትያን ኣኮርድዮንስ ክርኢ ከለኹ ሃረመኒ', 'ኣብ  ቲ ሳጹን ዝርከብ  ን ጸሓይ ኣዝዩ ዝጸልኦ ኮይኑ   እቲ ናይ ኣንድሮይድ ትርጕም ግን ክሳብ', 'ሓድሽ ናይ  ኣፕ ሃርፐር ዘተኣማምን ናይ ሕሳብ ሓቂ ክኸውን ኣይክእልን እዩ   እንተኾነ ግን ነዚ ኤልክሳን42 ናበይ ገጽና ንኸይድ ከም ዝነበርና ምጽባይ', 'ሰባት ናጻ ክዀኑ ኣለዎም   ኣብ ጸሓይ ኒፕ ቦብ ማርሊ ኣይ ዝርከብ ቦታ ድማ ይፈልጡ እዮም', 'ኣብ ናይ ማኑጂንግ ኣይኦስን ማክስን 2ይ ክፋል ኤድ ቡክ ዓቢ ምንባብ ብዙሕ እዩ ዘመስገነኒ']


In [30]:
X_train, X_test, y_train, y_test = train_test_split(Comm, sentiment , test_size = 0.20, random_state = 42, shuffle = True)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = 0.20, random_state = 1, shuffle = True)
print(len(X_train))
print(len(X_val))
print(len(X_test))

3840
960
1200


In [31]:
import time
import torch 
from sentence_transformers import SentenceTransformer
from torch import nn, optim, tensor
from torch.nn import functional as F
encoder = SentenceTransformer('sentence-transformers/LaBSE')
print('Encoding segments...')

Encoding segments...


In [32]:
model = SentenceTransformer('sentence-transformers/LaBSE')
embeddingtr = model.encode(X_train, batch_size = 128, convert_to_numpy = True, show_progress_bar = True)
embeddingts = model.encode(X_test, batch_size = 128, convert_to_numpy = True, show_progress_bar = True)

Batches:   0%|          | 0/30 [00:00<?, ?it/s]

Batches:   0%|          | 0/10 [00:00<?, ?it/s]

In [33]:
from sklearn.svm import SVC
clf = SVC(gamma ='auto')
clf.fit(embeddingtr, y_train)
y_pred = clf.predict(embeddingts)


In [34]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.49916666666666665


In [35]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(max_depth=9, random_state=0)
clf1.fit(embeddingtr, y_train)

y_pred1 = clf1.predict(embeddingts)
print(accuracy_score(y_test, y_pred1))

0.5191666666666667


In [36]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test, y_pred1)

print('Confusion Matrix\n')
print(confusion)

Confusion Matrix

[[569   0  30]
 [147   0  28]
 [369   3  54]]
