In [1]:
import numpy as np 
import re, nltk
from numpy import array 
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences 
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense 
from keras.layers import Flatten
from keras.layers.embeddings import Embedding
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
df1= pd.read_csv(r'ALL_language.csv', encoding = "utf-8")
df = df1.sample(frac =1)
display(df)

English  \
16599          set alarm every 10 minutes for 20 minutes   
11613                            did it rain yesterday ?   
19093                  is it going to get cold tonight ?   
19666                       remove all alarms on sundays   
10697               delete every alarm that i have set .   
...                                                  ...   
16837  when should i start packing away my summer clo...   
7343             what is the temperature outside today ?   
15031                   set my alarm for 4 am tomorrow .   
998               how long until alarm on timer goes off   
10264               do i need to dress for hot weather ?   

                                     Amharic  \
16599  ለ 20 ደቂቃዎች በየደረጃው ሁሉንም 10 ደቂቃዎችን ያዘጋጁ   
11613                    ትናንት ዝናብን ዝናብ አደረገ?   
19093                         ዛሬ ማታ ቀዝቃዛ ነው?   
19666               እሑድ ላይ ሁሉንም ማንቂያዎች ያስወግዱ   
10697           ያዘጋጃቸውን ደወል እያንዳንዱን ደወል ሰርዝ.   
...                                      ...   
16837           የበጋዎትን ልብሶቼን ማሸግ ያለብኝ መቼ ነው?   
7343              ከዛሬ ውጭ ያለው የሙቀት መጠን ምንድነው?   
15031                      ነገን ለ 4 ሰዓት ያዘጋጁ.   
998             ሰዓት ቆጣሪው እስኪወጣ ድረስ ምን ያህል ጊዜ   
10264            ለሞቃት የአየር ጠባይ አለባበስ እፈልጋለሁ?   

                                              Lithuanian  \
16599      Nustatykite aliarmą kas 10 minučių 20 minučių   
11613                                   Ar vakar lietus?   
19093                            Ar šį vakarą bus šalta?   
19666              Išimkite visus aliarmus sekmadieniais   
10697       Ištrinkite kiekvieną mano nustatytą aliarmą.   
...                                                  ...   
16837  Kada turėčiau pradėti supakuoti savo vasaros d...   
7343                   Kokia temperatūra šiandien lauke?   
15031            Nustatykite savo žadintuvą rytoj 4 val.   
998                  Kiek laiko, kol bus išeis laikmatis   
10264               Ar man reikia apsirengti karštu oru?   

                                         Arabic  \
16599     اضبط المنبه كل 10 دقائق لمدة 20 دقيقة   
11613                              هل تمطر أمس؟   
19093                    هل ستصبح باردة الليلة؟   
19666            إزالة جميع الإنذارات يوم الأحد   
10697                 حذف كل إنذار قمت بتعيينه.   
...                                         ...   
16837  متى يجب أن أبدأ في تعبئة ملابسي الصيفية؟   
7343        ما هي درجة الحرارة في الخارج اليوم؟   
15031           اضبط إنذاري لمدة 4 صباحًا غدًا.   
998      كم من الوقت حتى ينفجر المنبه في المؤقت   
10264    هل أحتاج إلى ارتداء ملابس الطقس الحار؟   

                                                 Germany  Tigrinya  \
16599  Stellen Sie alle 10 Minuten für 20 Minuten Ala...       NaN   
11613                          hat es gestern geregnet ?       NaN   
19093                          Wird es heute Abend kalt?       NaN   
19666                 Entfernen Sie sonntags alle Alarme       NaN   
10697     Löschen Sie jeden Alarm, den ich gesetzt habe.       NaN   
...                                                  ...       ...   
16837  Wann sollte ich anfangen, meine Sommerkleidung...       NaN   
7343               Was ist die Temperatur heute draußen?       NaN   
15031     Stellen Sie meinen Alarm morgen für 4 Uhr ein.       NaN   
998    Wie lange dauert es, bis der Alarm am Timer au...       NaN   
10264           Muss ich mich für heißes Wetter kleiden?       NaN   

                                                  French  \
16599  régler l'alarme toutes les 10 minutes pendant ...   
11613                          Est-ce qu'il a plu hier ?   
19093              Est-ce que ça va faire froid ce soir?   
19666             Retirez toutes les alarmes le dimanche   
10697          Supprimez chaque alarme que j'ai définie.   
...                                                  ...   
16837  Quand dois-je commencer à emballer mes vêtemen...   
7343   Quelle est la température à l'extérieur aujour...   
15031  Définissez mon alarme pour 4 

In [3]:
sentence = df.French.values.tolist()
sentiment = df.Intent.values.tolist()
print(len(sentence))
print(len(sentiment))

22994
22994


In [4]:
import pandas as pd
df2= pd.read_csv(r'Prompt2chatgpt.csv', encoding = "utf-8")
df3 = df2.sample(frac =1)
display(df3)

English  \
1    Move my wake-up alarms to 7:45 AM for the enti...   
84                               Snooze for 5 minutes.   
153  When will the sun rise tomorrow on the east co...   
98                                            instance   
41   Change the alarm sound to a calming melody fro...   
..                                                 ...   
87          Please snooze for an additional 3 minutes.   
183                 What time is the sunrise tomorrow?   
139     What time is the sunset in the summer tonight?   
96             Activate snooze for an extra 6 minutes.   
38   Set my alarm to ring every 15 minutes until ac...   

                                            Amharic  \
1    የኔ ማንቂያ ደውሎቶችን ለ 8:45 የሚቀጥለውን ሳምንት ማስወጣት ይችላሉ?   
84                         SNOOZE ን ለ 12 ደቂቃዎች ያዘጋጁ   
153            ለምን የታመነ ዓመታዊ ሰዓት የፀሐይ መውጫ ምን ሰዓት ነው   
98                         እንደአንደኛው ፀሐይ ስትጠልቅ መቼ ነው   
41                      መልስ እስከዚህ ድረስ በየ 8 ደቂቃው ደወል   
..                                              ...   
87                         SNOOZE ን ለ 30 ደቂቃዎች ያዘጋጁ   
183             ለምን የታመነ ዓመታዊ ሰዓት ምን ያህል ጊዜ ከፍ ብሏል?   
139              እንደ አንደኛው ዛሬ ማታ ፀሐይ መቼ ነው የሚያደርገው?   
96                       ለማሸለፊያ ሁኔታ ለ 18 ደቂቃዎች ያዘጋጁ   
38                                   ሰኞ - አርብ ይድገሙት   

                                               Germany  \
1           Wiederhole den Alarm bis zum Ende von 2017   
84           Stellen Sie den Snooze auf 10 Minuten ein   
153             Wie spät ist der Sonnenaufgang morgen?   
98                    Wann geht die Sonne heute unter?   
41   Wiederhole den Alarm bis zum Ende des Jahres 2017   
..                                                 ...   
87          Setzen Sie den Alarm auf 15 Minuten Snooze   
183             Wie spät ist der Sonnenaufgang morgen?   
139               Wie spät geht die Sonne heute unter?   
96                    Snooze für zusätzliche 5 Minuten   
38               Wiederhole ihn von Montag bis Freitag   

                                             Lithuania  \
1            Pakartokite pabudimą iki 2017 m. pabaigos   
84                     Nustatykite snaudimą 14 minučių   
153                        Kada rytoj saulėtekis vyks?   
98                   Kada yra šiandieninis saulėlydis?   
41   Pakartokite žadintuvą kas 12 minutes, kol bus ...   
..                                                 ...   
87   Nustatykite aliarmą, kad snaudžiate dar 22 min...   
183                        Kada rytoj saulėtekis vyks?   
139                     Kada šį vakarą saulė leisiasi?   
96                               Nuplėškite 30 minutes   
38   Pakartokite žadintuvą kas 7 valandas iki lapkr...   

                                                French  \
1               Répète l'alarme jusqu'à la fin de 2017   
84             Réglez la répétition pendant 10 minutes   
153         Quelle heure est le lever du soleil demain   
98                      Quand est le coucher du soleil   
41              Répète l'alarme jusqu'à la fin de 2017   
..                                                 ...   
87   Réglez l'alarme pour répéter pendant 15 minute...   
183         Quelle heure est le lever du soleil demain   
139  À quelle heure le soleil se couche-t-il aujour...   
96                            Snooze pendant 5 minutes   
38                         Répète du lundi au vendredi   

                                                 Czech                 Intent  
1                    Opakujte alarm do konce roku 2017    alarm__modify_alarm  
84                       Nastavte odložení na 10 minut    alarm__snooze_alarm  
153                    V kolik je čas na východ slunce  weather__checkSunrise  
98                                 Kdy je západ slunce   weather__checkSunset  
41                   Opakujte alarm do konce roku 2017    alarm__modify_alarm  
..                                                 ...                    ...  
87   Nastavte alarm, aby se odložil po

In [5]:
sentence_1 = df3.Amharic.values.tolist()
sentiment_1 = df3.Intent.values.tolist()
print(len(sentence_1))
print(len(sentiment_1))

189
189


In [6]:
for a in sentence_1:
    sentence.append(a)
for b in sentiment_1:
    sentiment.append(b)

print(len(sentiment))
print(len(sentence))

23183
23183


In [7]:
print(len(df.Intent.unique()))
print(df.Intent.value_counts())

13
weather__find                10461
reminder__set_reminder        4081
alarm__set_alarm              3915
alarm__cancel_alarm           1307
reminder__cancel_reminder      813
alarm__show_alarms             705
reminder__show_reminders       600
alarm__modify_alarm            399
alarm__time_left_on_alarm      270
alarm__snooze_alarm            260
weather__checkSunset           103
weather__checkSunrise           79
alarm__set_alar                  1
Name: Intent, dtype: int64


In [8]:
sentrp = sentence[0:18560]
sentsp = sentence[18400:23196]
semtr = sentiment[0:18560]
semts = sentiment[18400:23196]
print(len(sentrp))
print(len(sentsp))
print(len(semtr))
print(len(semts))


18560
4783
18560
4783


In [9]:
print(sentrp[0:10])
print(sentsp[0:10])
print(semtr[0:10])
print(semts[0:10])

["régler l'alarme toutes les 10 minutes pendant 20 minutes", "Est-ce qu'il a plu hier ?", 'Est-ce que ça va faire froid ce soir?', 'Retirez toutes les alarmes le dimanche', "Supprimez chaque alarme que j'ai définie.", 'Donnez-moi une alarme en 15 minutes.', 'Veuillez effacer tous les rappels.', 'À quelle vitesse sont les vents de cet ouragan', 'Supprimez toutes les alarmes faites dans ce mois-ci.', 'Y aura-t-il du vent ce soir']
['Quelle est la basse température pour ce soir', "Réglez l'alarme pour 8 demain.", "Effacer toutes les alarmes enregistrées s'il vous plaît", "Est-ce qu'il pleut à St Louis en ce moment", "Est-ce que ça va être chaud aujourd'hui?", 'Alarme sonore toutes les 20 minutes', 'Y aura-t-il un blizzard demain', "Est-il censé être très chaud et humide aujourd'hui?", 'Montre-moi mes alarmes actuelles', 'sera-t-il supérieur à 41 en degrés Celsius pour Karachi']
['alarm__set_alarm', 'weather__find', 'weather__find', 'alarm__cancel_alarm', 'alarm__cancel_alarm', 'alarm__set

In [10]:
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer
import torch
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import seaborn as sns
model = SentenceTransformer('sentence-transformers/LaBSE')
embeddingtr = model.encode(sentrp, batch_size = 128, convert_to_numpy = True, show_progress_bar = True)
embeddingts = model.encode(sentsp, batch_size = 128, convert_to_numpy = True, show_progress_bar = True)

Batches:   0%|          | 0/145 [00:00<?, ?it/s]

Batches:   0%|          | 0/38 [00:00<?, ?it/s]

print(len(embeddingts))
print(len(embeddingtr))

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
frames = []
for idx, val in enumerate(sentsp):
    cos_va = cosine_similarity(embeddingts, embeddingtr)[idx]
    df1 = pd.DataFrame(sentrp, columns =['sentenc'])
    df1['position'] = df1.index.values
    
    df1['realsem'] = semts[idx]
    df1['new_cosine'] = (cos_va)
    query_sentence_cosine_df1 = df1.sort_values('new_cosine', ascending = False)
    df2 = query_sentence_cosine_df1[['sentenc', 'new_cosine','position','realsem']].head(3)
    frames.append(df2)
    result = pd.concat(frames)
display(result)

In [ ]:
for i in result['position']:
    result['pred'][i]= semtr[i]
display(result)

In [37]:
import numpy
Grp = []
subs = []
result['pred']
for i in result['pred']:
    Grp.append(i)
#print(Grp)
print(len(Grp))
print(type(Grp))
splits = np.array_split(Grp,len(sentsp))# no of testing sets
vote = []
for array in splits:
    vote.append(list(array))
print(vote)
gr = []
for el in vote:
    mx = max(set(el), key =el.count)
    gr.append(mx)
    
print(gr)
print(type(gr))
print(len(gr))

14349
<class 'list'>
[['weather__find', 'weather__find', 'weather__find'], ['weather__find', 'weather__find', 'weather__find'], ['weather__find', 'weather__find', 'weather__find'], ['alarm__set_alarm', 'alarm__modify_alarm', 'alarm__cancel_alarm'], ['weather__find', 'weather__find', 'weather__find'], ['weather__find', 'weather__find', 'weather__find'], ['weather__find', 'weather__find', 'weather__find'], ['weather__find', 'weather__find', 'weather__find'], ['weather__find', 'weather__find', 'weather__find'], ['alarm__snooze_alarm', 'alarm__cancel_alarm', 'alarm__snooze_alarm'], ['weather__find', 'weather__find', 'weather__find'], ['weather__find', 'weather__find', 'weather__find'], ['weather__find', 'weather__find', 'weather__find'], ['alarm__set_alarm', 'alarm__set_alarm', 'alarm__set_alarm'], ['weather__find', 'weather__find', 'weather__find'], ['reminder__set_reminder', 'reminder__show_reminders', 'reminder__show_reminders'], ['reminder__set_reminder', 'reminder__set_reminder', 'rem

In [38]:
from sklearn.metrics.pairwise import cosine_similarity
Fram = []
for idx, val in enumerate(sentsp):
    cos_va = cosine_similarity(embeddingts, embeddingtr)[idx]
    
    df1 = pd.DataFrame(sentrp, columns =['sentenc'])
    df1['position'] = df1.index.values
    df1['realsem'] = semts[idx]
    df1['new_cosine'] = (cos_va)
    query_sentence_cosine_df1 = df1.sort_values('new_cosine', ascending = False)
    res = query_sentence_cosine_df1[['sentenc', 'new_cosine','position','realsem']].head(1)
    Fram.append(res)
    reslt1= pd.concat(Fram)
display(reslt1)

sentenc  new_cosine  position  \
18400         Quel temps fait-il pour Chicago demain?    1.000000     18400   
18401        Une pluie attendue la semaine prochaine?    1.000000     18401   
18402                           Quel temps à la plage    1.000000     18402   
18403          faire couler mon alarme dans une heure    1.000000     18403   
18404              Comme c'est froid pour aujourd'hui    1.000000     18404   
...                                               ...         ...       ...   
5541                     Réglez l'alarme à 15 minutes    0.937903      5541   
8981                  Ajouter 10 minutes à mon alarme    0.978060      8981   
5541                     Réglez l'alarme à 15 minutes    0.937903      5541   
7491   À quelle heure le soleil se lève-t-il ce matin    0.911185      7491   
2319           À quelle heure est le lever du soleil?    0.967476      2319   

                     realsem  
18400          weather__find  
18401          weather__find  
18402          weather__find  
18403       alarm__set_alarm  
18404          weather__find  
...                      ...  
5541     alarm__snooze_alarm  
8981     alarm__modify_alarm  
5541     alarm__snooze_alarm  
7491   weather__checkSunrise  
2319   weather__checkSunrise  

[4783 rows x 4 columns]

In [39]:
reslt1['predic']= gr
display(reslt1) 

sentenc  new_cosine  position  \
18400         Quel temps fait-il pour Chicago demain?    1.000000     18400   
18401        Une pluie attendue la semaine prochaine?    1.000000     18401   
18402                           Quel temps à la plage    1.000000     18402   
18403          faire couler mon alarme dans une heure    1.000000     18403   
18404              Comme c'est froid pour aujourd'hui    1.000000     18404   
...                                               ...         ...       ...   
5541                     Réglez l'alarme à 15 minutes    0.937903      5541   
8981                  Ajouter 10 minutes à mon alarme    0.978060      8981   
5541                     Réglez l'alarme à 15 minutes    0.937903      5541   
7491   À quelle heure le soleil se lève-t-il ce matin    0.911185      7491   
2319           À quelle heure est le lever du soleil?    0.967476      2319   

                     realsem                 predic  
18400          weather__find          weather__find  
18401          weather__find          weather__find  
18402          weather__find          weather__find  
18403       alarm__set_alarm       alarm__set_alarm  
18404          weather__find          weather__find  
...                      ...                    ...  
5541     alarm__snooze_alarm       alarm__set_alarm  
8981     alarm__modify_alarm    alarm__modify_alarm  
5541     alarm__snooze_alarm       alarm__set_alarm  
7491   weather__checkSunrise  weather__checkSunrise  
2319   weather__checkSunrise  weather__checkSunrise  

[4783 rows x 5 columns]

In [40]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    display(reslt1)

sentenc  new_cosine  \
18400            Quel temps fait-il pour Chicago demain?    1.000000   
18401           Une pluie attendue la semaine prochaine?    1.000000   
18402                              Quel temps à la plage    1.000000   
18403             faire couler mon alarme dans une heure    1.000000   
18404                 Comme c'est froid pour aujourd'hui    1.000000   
18405              Quelle est la température de Buffalo?    1.000000   
18406                            Comme ça va faire chaud    1.000000   
18407               Ava-t-il atteindre 70 degrés demain?    1.000000   
18408          Dites-moi le temps à Tucson en ce moment.    1.000000   
18409                      Pouvez-vous somnoler l'alarme    1.000000   
18410           Y a-t-il de la neige dans les montagnes?    1.000000   
18411  Est-ce que ça va être au-dessus de quatre-ving...    1.000000   
4535                           À quel point aujourd'hui?    1.000000   
18413                  Définissez une alarme pour 8 h 59    1.000000   
18414                             Est-ce humide à Miami?    1.000000   
18415                         rappel à la liste complète    1.000000   
18416  Rappelez-moi d'ajouter de l'eau en bouteille à...    1.000000   
18417               Combien de temps jusqu'à mon alarme?    1.000000   
18418      Comment se passera-t-il au cours du week-end?    1.000000   
18419  Quand sommes-nous censés obtenir une pause de ...    1.000000   
18420                   Quels rappels ai-je pour demain?    1.000000   
18421  Rappelez-moi de m'arrêter et d'obtenir des cup...    1.000000   
18422                       Sera-ce du vent demain soir?    1.000000   
18423                Quel temps va-t-il faire ce samedi?    1.000000   
18424     Est-ce en dessous de 96 Fahrenheit ici ce soir    1.000000   
18425            Quelles sont les prévisions du week-end    1.000000   
18426  sera-t-il en dessous de 27 à Celsius à Pékin c...    1.000000   
18427                     Est-ce qu'il pleut en Floride?    1.000000   
18428                            Créer un nouveau rappel    1.000000   
18429       Quelle est la basse température en ce moment    1.000000   
18430                                  modifier l'alarme    1.000000   
18431  Rappelez-moi de retirer le gâteau du four en 1...    1.000000   
18432    Y a-t-il la pluie des prévisions cette semaine?    1.000000   
18433                   Ajouter un rappel pour la banque    1.000000   
18434  Rappelez-moi d'acheter des couches à l'épiceri...    1.000000   
18435  Va-t-il pleuvoir dans les deux prochaines heures?    1.000000   
18436               Quel temps va-t-il faire demain soir    1.000000   
18437                           Est-ce que ça va saluer?    1.000000   
18438                   Quel temps fait-il cette semaine    1.000000   
18439  Rappelle-moi de prendre de la nourriture pour ...    1.000000   
18440              Configurez l'alarme pour demain à 7 h    1.000000   
18441                            faire une alarme pour 7    1.000000   
18442                              Prévisions de 5 jours    1.000000   
18443                     Quelle est la chance de neige?    1.000000   
18444                   Réinitialisez toutes les alarmes    1.000000   
18445                            Prévisions pour demain.    1.000000   
18446                  Supprimer les alarmes pour demain    1.000000   
18447  Rappelle-moi de prendre de la nourriture quand...    1.000000   
18448  régler l'alarme toutes les cinq minutes pendan...    1.000000   
18449                   Est-ce nuageux toute la journée?    1.000000   
18450                               Une chance de neige?    1.000000   
7707                   Va-t-il pleuvoir tout le week-end    1.000000   
18452  Annulez mon rappel pour acheter du pain au mag...    1.000000   
18453          Rappelez-moi de faire des courses ce soir    1.000000   
18454  En 15 minutes, commencez une alarme pendant 30...    1.000000   
18455            

In [41]:
import pandas as pd
true_class = reslt1["realsem"].to_numpy()
pred_class = reslt1["predic"].to_numpy()

In [42]:
Accuracy = sum(np.array(pred_class)==np.array(true_class))/float(len(true_class))
print(Accuracy)

0.9441772945849884


In [43]:
print(true_class)
print(pred_class)
print(true_class.dtype)
print(pred_class.dtype)
true_clas = true_class.astype(str)
pred_clas = pred_class.astype(str)
print(true_clas.dtype)
print(pred_clas.dtype)

['weather__find' 'weather__find' 'weather__find' ... 'alarm__snooze_alarm'
 'weather__checkSunrise' 'weather__checkSunrise']
['weather__find' 'weather__find' 'weather__find' ... 'alarm__set_alarm'
 'weather__checkSunrise' 'weather__checkSunrise']
object
object
<U25
<U25


In [44]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
cf_matrix = confusion_matrix(true_clas, pred_clas)
print(cf_matrix)

[[ 232    1   10    0    3    0    0    3    1    0    0    0    0]
 [   3   74   28    1    2    0    0    0   10    0    0    0    9]
 [   6    4  717    3    4    1    0    0   11    0    0    0    0]
 [   2    0    5  105    0    3    0    0    0    3    0    0    0]
 [   9    0   33    1   58    0    0    0    0    0    0    0    0]
 [   0    0    0    5    0   53    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    1]
 [   8    0    0    0    0    0    0  143   13    0    0    0    0]
 [   0    0   31    0    1    0    0    5  791    2    0    0    1]
 [   0    0    0    5    0    2    0    2   14   96    0    0    1]
 [   0    0    0    0    0    0    0    0    0    0   55    5    0]
 [   0    0    0    0    0    0    0    0    0    0    2   56    5]
 [   0    0    1    2    0    0    0    0    1    1    1    2 2136]]


In [45]:
from sklearn import metrics
print(metrics.classification_report(true_clas, pred_clas))

                           precision    recall  f1-score   support

      alarm__cancel_alarm       0.89      0.93      0.91       250
      alarm__modify_alarm       0.94      0.58      0.72       127
         alarm__set_alarm       0.87      0.96      0.91       746
       alarm__show_alarms       0.86      0.89      0.88       118
      alarm__snooze_alarm       0.85      0.57      0.69       101
alarm__time_left_on_alarm       0.90      0.91      0.91        58
                      nan       0.00      0.00      0.00         1
reminder__cancel_reminder       0.93      0.87      0.90       164
   reminder__set_reminder       0.94      0.95      0.95       831
 reminder__show_reminders       0.94      0.80      0.86       120
    weather__checkSunrise       0.95      0.92      0.93        60
     weather__checkSunset       0.89      0.89      0.89        63
            weather__find       0.99      1.00      0.99      2144

                 accuracy                           0.94    

C:\Users\senug\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\senug\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\senug\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
